[build]
  base = "caring4carers-nextjs"
  command = "npm install && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 